version: '3'
services:
  db:
    image: mysql:5.7
    container_name: payfast_db
    volumes: 
      - ./banco/access/:/etc/access/
      - ./banco/data/:/var/lib/mysql/
      - ./banco/datafiles/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payfast
    command: "--innodb_use_native_aio=0"
    ports: 
      - 3306:3306