apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-mysql
spec:
  selector:
    matchLabels:
      name: banco-payfast
  serviceName: payfast-db
  template:
    metadata:
      labels:
       name: banco-payfast
    spec:
      containers:
        - name: container-mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "payfast"
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          volumeMounts:
            - name: volume-mysql
              mountPath: /var/lib/mysql
      volumes:
          - name: volume-mysql
            persistentVolumeClaim:
              claimName: configuracao-mysql
